### ISSUE TITLE
Question about remote users

### ISSUE THREAD

**Issue by redbox-cdn** [martensson/vaban#2]
Hi it's nice package!

Is it possible to purge by remote user and authentication ?

Ex:

curl -i https://remotehostname:4000/v1/service/group1/ban -d '{"Vcl":"req.http.Host == 'example.com'"}' -H 'Content-Type: application/json' 'APIhashkey xxxxxxxxxxxxx'

 This means, the setting per user APIhashkey in the VCL , the remote user can banned cache using APIhashkey.

Thanks!

**Comment by martensson** [comment]
Hi @redbox2000,

I am happy you like Vaban. And if I understand your question correctly you want some type of authentication based on API Keys? Every user who bans should have his own key?

Best regards,
Benjamin

**Comment by redbox2000** [comment]
Hi martensson

Yes, your correct. 
I already setting the vhost for every user on varnish.

Ex;
userA domainname1.com  api key is key1111

banned command
curl -i https://vabanserver.com:4000/v1/service/group1/ban -d '{"Vcl":"req.http.Host == 'domainname1.com'"}' -H 'Content-Type: application/json' 'APIkey: key111'

userB domainname2.com api key is key222

banned command
curl -i https://vabanserver.com:4000/v1/service/group1/ban -d '{"Vcl":"req.http.Host == 'domainname2.com'"}' -H 'Content-Type: application/json' 'APIkey: key222'
 
Currently, the every vhost users removing cache via my PHP form. (It is not simple....)
So I want to remove the cache via API. 
But in my case the cache remove action must authentication. 

I am not 100% sure If the Vaban will be able to add own header, It can be authenticated.

Best regards.

**Comment by martensson** [comment]
Hi @redbox2000,

Sounds like an interesting idea, and I might be able to implement some optional authentication.
In our case we don't need any authentication since we control the clients who communicate with Vaban. But it might interesting to look at anyhow. I will take a look at JSON Web Token (JWT) and see what I can do :)

**Comment by redbox2000** [comment]
Hi martensso

Thank you for considering my request.

I am not sure JWT but if vaban will be handle  token based authentication, it very useful!!

Currently, I am considering authentication using host header.
The host header is include authkey instead of hostname.

Here is my purge vcl.

sub vcl_recv {

if (req.request == "PURGE") {
                ban("obj.http.X-HOST ~ "+ req.http.host + " && obj.http.X-URL ~ " + req.url);
                error 200 "banned.";
                                            }
                                }
}

sub vcl_fetch {
if (req.http.host == "origin.domain.name") {
        set beresp.http.X-URL = req.url;
        set beresp.http.X-HOST = "key";
}

The X-HOST = purge key instead of host name.

In case of curl.
curl -X PURGE -H Host:key varniship/test.txt

In case of vban?

curl -i http://127.0.0.1:4000/v1/service/service1/ban -d '{"Pattern":"test.txt"}' '{"Vcl":"req.http.Host == 'key'"}' -H 'Content-Type: application/json'

but it could not work for me. 

I don't understand my mistake.
